### ISSUE TITLE
Add support for API Ollama

### ISSUE THREAD

**Issue by jcesclapez** [thepersonalaicompany/amurex#29]
It would be nice if you could add support to ollama and have a 100% private service.

Thank you very much.

**Comment by sansyrox** [comment]
Hey @jcesclapez 👋 

We do support it :D You can find the implementation here - https://github.com/thepersonalaicompany/amurex-backend

Maybe we need to update it the documentation to make it more prominent.

**Comment by jcesclapez** [comment]
Hi @sansyrox 

I'm sorry but I can't see where is the way to configure it for the ollama api.

**Comment by arsenkylyshbek** [comment]
Hi @jcesclapez 👋

We will update the documentation soon to make it more clear.

I've just uploaded a `.env.example` file to our [backend repo](https://github.com/thepersonalaicompany/amurex-backend). To make the project use Ollama local models instead of OpenAI and Groq APIs, you simply need to set `CLIENT_MODE` to `LOCAL`.

If you have an Ollama desktop application, you can check all the installed models first:
`ollama list`

and make sure that you are using any of the available models in the index.py file. We are using `llama3.2` by default, but you can use any other model you've pulled from Ollama.

**Comment by sansyrox** [comment]
https://github.com/thepersonalaicompany/amurex-backend/issues/10 

Moved here.
